include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_dynamic_calls: false
    avoid_function_literals_in_foreach_calls: false
    deprecated_member_use: false
    directives_ordering: true
    prefer_single_quotes: true
    sort_pub_dependencies: false

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  exclude:
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "lib/core/l10n/generated/**"
