# yaml-language-server: $schema=https://json.schemastore.org/codecov.json
coverage:
  range: 70...100
  round: down
  precision: 2

ignore:
  - "**/injection.dart"
  - "**/providers.dart"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.config.dart"
  - "**/generated/**"
