name: kweeksnews_app
description: Flutter app for KweeksNews site

version: 2.0.0+2
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio_http_cache:
    git:
      url: https://github.com/vrtdev/dio-http-cache.git
      ref: feature/nullsafety-dio4
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  flutter_html: ^2.1.0
  flutter_riverpod: ^0.14.0+3
  font_awesome_flutter: ^9.1.0
  get_it: ^7.1.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  infinite_scroll_pagination: ^3.0.1+1
  injectable: ^1.4.1
  internet_connection_checker: ^0.0.1+1
  intl: ^0.17.0
  moor: ^4.3.2
  moor_flutter: ^4.0.0
  nil: ^1.1.1
  package_info: ^2.0.2
  photo_view: ^0.11.1
  share: ^2.0.4
  shimmer: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  url_launcher: ^6.0.6
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: null
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.1.0
  injectable_generator: ^1.4.1
  lint: ^1.5.3
  moor_generator: ^4.3.1

flutter_icons:
  image_path: assets/ic_launcher.png
  adaptive_icon_background: "#FF000000"
  android: "ic_launcher"
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/error.png
    - assets/no_data.png
    - assets/placeholder.png
    - assets/search.png
    - assets/dark/icon.png
    - assets/light/icon.png

  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri/Amiri-Bold.ttf
        - asset: fonts/Amiri/Amiri-BoldItalic.ttf
        - asset: fonts/Amiri/Amiri-Italic.ttf
        - asset: fonts/Amiri/Amiri-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf

    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
        - asset: fonts/Quicksand/Quicksand-Light.ttf
        - asset: fonts/Quicksand/Quicksand-Medium.ttf
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
        - asset: fonts/Quicksand/Quicksand-SemiBold.ttf
